name: strongbolt
description: A application based on Matrix protocol.
uses-material-design: true
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.35.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  adobe_xd: ^2.0.1
  flutter_svg: ^2.2.0
  random_string: ^2.3.1
  bitcoin_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/